// theme/theme.js
import { palette } from './colors';

export const lightTheme = {
  background: palette.light_background,
  gradientBackground: palette.light_gradient,
  cardBackground: palette.light_card,
  cardBackgroundAlt: '#f1f5f9',
  text: palette.light_text,
  textSecondary: palette.light_text_secondary,
  textTertiary: '#9a9ab0',
  inputBackground: palette.light_card,
  inputBackgroundFocused: palette.light_card,
  inputBackgroundError: '#fff5f5',
  inputText: palette.light_text,
  inputIcon: '#7a7a9a',
  placeholder: '#9a9ab0',
  accent: palette.primary,
  accentSecondary: palette.primaryDark,
  buttonDisabled: '#d0d0e0',
  error: palette.error,
  success: palette.success,
  divider: '#d0d0e0',
  dividerText: '#9a9ab0',
  infoBackground: 'rgba(243, 156, 18, 0.1)',
  infoBorder: palette.primary,
  infoText: '#5a5a7a',
  borderTransparent: 'transparent',
  borderColor: '#e2e8f0',
  iconCircleBackground: 'rgba(243, 156, 18, 0.15)',
};

export const darkTheme = {
  background: palette.dark_background,
  gradientBackground: palette.dark_gradient,
  cardBackground: palette.dark_card,
  cardBackgroundAlt: '#252550',
  text: palette.dark_text,
  textSecondary: palette.dark_text_secondary,
  textTertiary: palette.dark_text_tertiary,
  inputBackground: palette.light_card,
  inputBackgroundFocused: '#fefefe',
  inputBackgroundError: '#fff5f5',
  inputText: '#333',
  inputIcon: '#666',
  placeholder: '#999',
  accent: palette.accent,
  accentSecondary: palette.accentSecondary,
  buttonDisabled: '#4a4a6a',
  error: '#FF6B6B',
  success: '#4CAF50',
  divider: '#333',
  dividerText: '#666',
  infoBackground: 'rgba(253, 173, 0, 0.1)',
  infoBorder: palette.accent,
  infoText: '#8a8aa0',
  borderTransparent: 'transparent',
  borderColor: '#2d2d5a',
  iconCircleBackground: 'rgba(253, 173, 0, 0.15)',
};